apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfig
data:
  MYSQL_ROOT_PASSWORD: example_password
  MYSQL_DATABASE: my_database
  MYSQL_USER: my_user
  MYSQL_PASSWORD: my_password
  create_table.sql: |
    CREATE TABLE IF NOT EXISTS form_data (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );