apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 192.168.49.2:5000/wepapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
         requests:
          memory: "16Mi"
          cpu: "62.5m"
         limits:
          memory: "32Mi"
          cpu: "62.5m"